/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'contactName' : string,
  'createdAt' : Time,
  'email' : string,
  'website' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface ClientRevenue {
  'clientId' : bigint,
  'companyName' : string,
  'totalRevenue' : bigint,
}
export interface CompanySettings {
  'email' : string,
  'website' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface Invoice {
  'id' : bigint,
  'status' : { 'paid' : null } |
    { 'unpaid' : null } |
    { 'draft' : null },
  'lineItems' : Array<InvoiceLineItem>,
  'ourCompanyName' : string,
  'taxPercent' : bigint,
  'clientWebsite' : string,
  'createdAt' : Time,
  'clientEmail' : string,
  'dueDate' : Time,
  'discountPercent' : bigint,
  'ourEmail' : string,
  'clientAddress' : string,
  'grandTotal' : bigint,
  'invoiceDate' : Time,
  'ourWebsite' : string,
  'updatedAt' : Time,
  'invoiceNumber' : string,
  'projectId' : bigint,
  'costCenter' : string,
  'clientPhone' : string,
  'ourAddress' : string,
  'ourPhone' : string,
  'paymentTerms' : string,
  'clientCompanyName' : string,
  'subtotal' : bigint,
  'invoiceMonth' : string,
}
export interface InvoiceLineItem {
  'date' : Time,
  'hourlyRate' : bigint,
  'visitTime' : bigint,
  'description' : string,
  'totalAmount' : bigint,
  'travelCost' : bigint,
  'materialCost' : bigint,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'userId' : Principal,
  'notificationType' : { 'info' : null } |
    { 'deadline' : null } |
    { 'payment' : null },
  'createdAt' : Time,
  'read' : boolean,
  'message' : string,
}
export interface Project {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null },
  'clientId' : bigint,
  'techBankDetails' : string,
  'timeIn' : Time,
  'clientPaid' : boolean,
  'visitLocation' : string,
  'techAgreedRate' : bigint,
  'createdAt' : Time,
  'visitDate' : Time,
  'totalTime' : bigint,
  'projectHandleClient' : string,
  'updatedAt' : Time,
  'progress' : bigint,
  'techDetails' : string,
  'clientAgreedRate' : bigint,
  'travelCost' : bigint,
  'profit' : bigint,
  'timeOut' : Time,
  'materialCost' : bigint,
  'clientCompanyName' : string,
  'projectHandleTeam' : string,
  'techPaid' : boolean,
}
export interface ProjectPerformance {
  'pendingCount' : bigint,
  'cancelledCount' : bigint,
  'completedCount' : bigint,
  'averageProfit' : bigint,
  'totalProfit' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'hoursSpent' : bigint,
  'completed' : boolean,
  'description' : string,
  'projectId' : bigint,
}
export type Time = bigint;
export interface UserEntry {
  'principal' : Principal,
  'role' : UserRole,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[Client], bigint>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'createNotification' : ActorMethod<[Notification], bigint>,
  'createProject' : ActorMethod<[Project], bigint>,
  'createTask' : ActorMethod<[Task], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getCompanySettings' : ActorMethod<[], [] | [CompanySettings]>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getMonthlyEarnings' : ActorMethod<[string], bigint>,
  'getNotificationsByUser' : ActorMethod<[Principal], Array<Notification>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectPerformance' : ActorMethod<[], ProjectPerformance>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTopClientsByRevenue' : ActorMethod<[bigint], Array<ClientRevenue>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'listAllUsers' : ActorMethod<[], Array<UserEntry>>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listInvoicesByProject' : ActorMethod<[bigint], Array<Invoice>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listTasksByProject' : ActorMethod<[bigint], Array<Task>>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'registerCaller' : ActorMethod<[], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[bigint, Client], undefined>,
  'updateCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'updateInvoice' : ActorMethod<[bigint, Invoice], undefined>,
  'updateProject' : ActorMethod<[bigint, Project], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];