/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceLineItem = IDL.Record({
  'date' : Time,
  'hourlyRate' : IDL.Nat,
  'visitTime' : IDL.Nat,
  'description' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'travelCost' : IDL.Nat,
  'materialCost' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'draft' : IDL.Null,
  }),
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'ourCompanyName' : IDL.Text,
  'taxPercent' : IDL.Nat,
  'clientWebsite' : IDL.Text,
  'createdAt' : Time,
  'clientEmail' : IDL.Text,
  'dueDate' : Time,
  'discountPercent' : IDL.Nat,
  'ourEmail' : IDL.Text,
  'clientAddress' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'invoiceDate' : Time,
  'ourWebsite' : IDL.Text,
  'updatedAt' : Time,
  'invoiceNumber' : IDL.Text,
  'projectId' : IDL.Nat,
  'costCenter' : IDL.Text,
  'clientPhone' : IDL.Text,
  'ourAddress' : IDL.Text,
  'ourPhone' : IDL.Text,
  'paymentTerms' : IDL.Text,
  'clientCompanyName' : IDL.Text,
  'subtotal' : IDL.Nat,
  'invoiceMonth' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Variant({
    'info' : IDL.Null,
    'deadline' : IDL.Null,
    'payment' : IDL.Null,
  }),
  'createdAt' : Time,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'clientId' : IDL.Nat,
  'techBankDetails' : IDL.Text,
  'timeIn' : Time,
  'clientPaid' : IDL.Bool,
  'visitLocation' : IDL.Text,
  'techAgreedRate' : IDL.Nat,
  'createdAt' : Time,
  'visitDate' : Time,
  'totalTime' : IDL.Nat,
  'projectHandleClient' : IDL.Text,
  'updatedAt' : Time,
  'progress' : IDL.Nat,
  'techDetails' : IDL.Text,
  'clientAgreedRate' : IDL.Nat,
  'travelCost' : IDL.Nat,
  'profit' : IDL.Nat,
  'timeOut' : Time,
  'materialCost' : IDL.Nat,
  'clientCompanyName' : IDL.Text,
  'projectHandleTeam' : IDL.Text,
  'techPaid' : IDL.Bool,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'hoursSpent' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CompanySettings = IDL.Record({
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProjectPerformance = IDL.Record({
  'pendingCount' : IDL.Nat,
  'cancelledCount' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'averageProfit' : IDL.Nat,
  'totalProfit' : IDL.Nat,
});
export const ClientRevenue = IDL.Record({
  'clientId' : IDL.Nat,
  'companyName' : IDL.Text,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([Client], [IDL.Nat], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
  'createProject' : IDL.Func([Project], [IDL.Nat], []),
  'createTask' : IDL.Func([Task], [IDL.Nat], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
  'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getMonthlyEarnings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getNotificationsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectPerformance' : IDL.Func([], [ProjectPerformance], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTopClientsByRevenue' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClientRevenue)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listInvoicesByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listTasksByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
  'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
  'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
  'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceLineItem = IDL.Record({
    'date' : Time,
    'hourlyRate' : IDL.Nat,
    'visitTime' : IDL.Nat,
    'description' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'travelCost' : IDL.Nat,
    'materialCost' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'unpaid' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'ourCompanyName' : IDL.Text,
    'taxPercent' : IDL.Nat,
    'clientWebsite' : IDL.Text,
    'createdAt' : Time,
    'clientEmail' : IDL.Text,
    'dueDate' : Time,
    'discountPercent' : IDL.Nat,
    'ourEmail' : IDL.Text,
    'clientAddress' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'invoiceDate' : Time,
    'ourWebsite' : IDL.Text,
    'updatedAt' : Time,
    'invoiceNumber' : IDL.Text,
    'projectId' : IDL.Nat,
    'costCenter' : IDL.Text,
    'clientPhone' : IDL.Text,
    'ourAddress' : IDL.Text,
    'ourPhone' : IDL.Text,
    'paymentTerms' : IDL.Text,
    'clientCompanyName' : IDL.Text,
    'subtotal' : IDL.Nat,
    'invoiceMonth' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Variant({
      'info' : IDL.Null,
      'deadline' : IDL.Null,
      'payment' : IDL.Null,
    }),
    'createdAt' : Time,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'clientId' : IDL.Nat,
    'techBankDetails' : IDL.Text,
    'timeIn' : Time,
    'clientPaid' : IDL.Bool,
    'visitLocation' : IDL.Text,
    'techAgreedRate' : IDL.Nat,
    'createdAt' : Time,
    'visitDate' : Time,
    'totalTime' : IDL.Nat,
    'projectHandleClient' : IDL.Text,
    'updatedAt' : Time,
    'progress' : IDL.Nat,
    'techDetails' : IDL.Text,
    'clientAgreedRate' : IDL.Nat,
    'travelCost' : IDL.Nat,
    'profit' : IDL.Nat,
    'timeOut' : Time,
    'materialCost' : IDL.Nat,
    'clientCompanyName' : IDL.Text,
    'projectHandleTeam' : IDL.Text,
    'techPaid' : IDL.Bool,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'hoursSpent' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CompanySettings = IDL.Record({
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProjectPerformance = IDL.Record({
    'pendingCount' : IDL.Nat,
    'cancelledCount' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'averageProfit' : IDL.Nat,
    'totalProfit' : IDL.Nat,
  });
  const ClientRevenue = IDL.Record({
    'clientId' : IDL.Nat,
    'companyName' : IDL.Text,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([Client], [IDL.Nat], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'createNotification' : IDL.Func([Notification], [IDL.Nat], []),
    'createProject' : IDL.Func([Project], [IDL.Nat], []),
    'createTask' : IDL.Func([Task], [IDL.Nat], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getMonthlyEarnings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getNotificationsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectPerformance' : IDL.Func([], [ProjectPerformance], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTopClientsByRevenue' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClientRevenue)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listInvoicesByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listTasksByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([IDL.Nat, Client], [], []),
    'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
    'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [], []),
    'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };