/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Client {
    id: bigint;
    contactName: string;
    createdAt: Time;
    email: string;
    website: string;
    address: string;
    companyName: string;
    phone: string;
}
export type Time = bigint;
export interface ProjectPerformance {
    pendingCount: bigint;
    cancelledCount: bigint;
    completedCount: bigint;
    averageProfit: bigint;
    totalProfit: bigint;
}
export interface Notification {
    id: bigint;
    title: string;
    userId: Principal;
    notificationType: Variant_info_deadline_payment;
    createdAt: Time;
    read: boolean;
    message: string;
}
export interface Task {
    id: bigint;
    title: string;
    createdAt: Time;
    hoursSpent: bigint;
    completed: boolean;
    description: string;
    projectId: bigint;
}
export interface CompanySettings {
    email: string;
    website: string;
    address: string;
    companyName: string;
    phone: string;
}
export interface Invoice {
    id: bigint;
    status: Variant_paid_unpaid_draft;
    lineItems: Array<InvoiceLineItem>;
    ourCompanyName: string;
    taxPercent: bigint;
    clientWebsite: string;
    createdAt: Time;
    clientEmail: string;
    dueDate: Time;
    discountPercent: bigint;
    ourEmail: string;
    clientAddress: string;
    grandTotal: bigint;
    invoiceDate: Time;
    ourWebsite: string;
    updatedAt: Time;
    invoiceNumber: string;
    projectId: bigint;
    costCenter: string;
    clientPhone: string;
    ourAddress: string;
    ourPhone: string;
    paymentTerms: string;
    clientCompanyName: string;
    subtotal: bigint;
    invoiceMonth: string;
}
export interface Project {
    id: bigint;
    status: Variant_cancelled_pending_completed;
    clientId: bigint;
    techBankDetails: string;
    timeIn: Time;
    clientPaid: boolean;
    visitLocation: string;
    techAgreedRate: bigint;
    createdAt: Time;
    visitDate: Time;
    totalTime: bigint;
    projectHandleClient: string;
    updatedAt: Time;
    progress: bigint;
    techDetails: string;
    clientAgreedRate: bigint;
    travelCost: bigint;
    profit: bigint;
    timeOut: Time;
    materialCost: bigint;
    clientCompanyName: string;
    projectHandleTeam: string;
    techPaid: boolean;
}
export interface ClientRevenue {
    clientId: bigint;
    companyName: string;
    totalRevenue: bigint;
}
export interface UserProfile {
    name: string;
}
export interface InvoiceLineItem {
    date: Time;
    hourlyRate: bigint;
    visitTime: bigint;
    description: string;
    totalAmount: bigint;
    travelCost: bigint;
    materialCost: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_completed {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum Variant_info_deadline_payment {
    info = "info",
    deadline = "deadline",
    payment = "payment"
}
export enum Variant_paid_unpaid_draft {
    paid = "paid",
    unpaid = "unpaid",
    draft = "draft"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(input: Client): Promise<bigint>;
    createInvoice(input: Invoice): Promise<bigint>;
    createNotification(notification: Notification): Promise<bigint>;
    createProject(input: Project): Promise<bigint>;
    createTask(input: Task): Promise<bigint>;
    deleteClient(clientId: bigint): Promise<void>;
    deleteInvoice(invoiceId: bigint): Promise<void>;
    deleteNotification(notificationId: bigint): Promise<void>;
    deleteProject(projectId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(clientId: bigint): Promise<Client | null>;
    getCompanySettings(): Promise<CompanySettings | null>;
    getInvoice(invoiceId: bigint): Promise<Invoice | null>;
    getMonthlyEarnings(month: string): Promise<bigint>;
    getNotificationsByUser(userId: Principal): Promise<Array<Notification>>;
    getProject(projectId: bigint): Promise<Project | null>;
    getProjectPerformance(): Promise<ProjectPerformance>;
    getTask(taskId: bigint): Promise<Task | null>;
    getTopClientsByRevenue(limit: bigint): Promise<Array<ClientRevenue>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllInvoices(): Promise<Array<Invoice>>;
    listClients(): Promise<Array<Client>>;
    listInvoicesByProject(projectId: bigint): Promise<Array<Invoice>>;
    listProjects(): Promise<Array<Project>>;
    listTasksByProject(projectId: bigint): Promise<Array<Task>>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(clientId: bigint, input: Client): Promise<void>;
    updateCompanySettings(settings: CompanySettings): Promise<void>;
    updateInvoice(invoiceId: bigint, input: Invoice): Promise<void>;
    updateProject(projectId: bigint, input: Project): Promise<void>;
    updateTask(taskId: bigint, input: Task): Promise<void>;
}
import type { Client as _Client, CompanySettings as _CompanySettings, Invoice as _Invoice, InvoiceLineItem as _InvoiceLineItem, Notification as _Notification, Project as _Project, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: Client): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_Notification_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_Notification_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProject(arg0: Project): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanySettings(): Promise<CompanySettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyEarnings(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyEarnings(arg0);
            return result;
        }
    }
    async getNotificationsByUser(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByUser(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByUser(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectPerformance(): Promise<ProjectPerformance> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectPerformance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectPerformance();
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopClientsByRevenue(arg0: bigint): Promise<Array<ClientRevenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopClientsByRevenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopClientsByRevenue(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllInvoices();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllInvoices();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients();
            return result;
        }
    }
    async listInvoicesByProject(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoicesByProject(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoicesByProject(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByProject(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByProject(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updateCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanySettings(arg0);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_Invoice_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_Project_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_Project_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Invoice_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySettings]): CompanySettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        paid: null;
    } | {
        unpaid: null;
    } | {
        draft: null;
    };
    lineItems: Array<_InvoiceLineItem>;
    ourCompanyName: string;
    taxPercent: bigint;
    clientWebsite: string;
    createdAt: _Time;
    clientEmail: string;
    dueDate: _Time;
    discountPercent: bigint;
    ourEmail: string;
    clientAddress: string;
    grandTotal: bigint;
    invoiceDate: _Time;
    ourWebsite: string;
    updatedAt: _Time;
    invoiceNumber: string;
    projectId: bigint;
    costCenter: string;
    clientPhone: string;
    ourAddress: string;
    ourPhone: string;
    paymentTerms: string;
    clientCompanyName: string;
    subtotal: bigint;
    invoiceMonth: string;
}): {
    id: bigint;
    status: Variant_paid_unpaid_draft;
    lineItems: Array<InvoiceLineItem>;
    ourCompanyName: string;
    taxPercent: bigint;
    clientWebsite: string;
    createdAt: Time;
    clientEmail: string;
    dueDate: Time;
    discountPercent: bigint;
    ourEmail: string;
    clientAddress: string;
    grandTotal: bigint;
    invoiceDate: Time;
    ourWebsite: string;
    updatedAt: Time;
    invoiceNumber: string;
    projectId: bigint;
    costCenter: string;
    clientPhone: string;
    ourAddress: string;
    ourPhone: string;
    paymentTerms: string;
    clientCompanyName: string;
    subtotal: bigint;
    invoiceMonth: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        ourCompanyName: value.ourCompanyName,
        taxPercent: value.taxPercent,
        clientWebsite: value.clientWebsite,
        createdAt: value.createdAt,
        clientEmail: value.clientEmail,
        dueDate: value.dueDate,
        discountPercent: value.discountPercent,
        ourEmail: value.ourEmail,
        clientAddress: value.clientAddress,
        grandTotal: value.grandTotal,
        invoiceDate: value.invoiceDate,
        ourWebsite: value.ourWebsite,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        projectId: value.projectId,
        costCenter: value.costCenter,
        clientPhone: value.clientPhone,
        ourAddress: value.ourAddress,
        ourPhone: value.ourPhone,
        paymentTerms: value.paymentTerms,
        clientCompanyName: value.clientCompanyName,
        subtotal: value.subtotal,
        invoiceMonth: value.invoiceMonth
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: Principal;
    notificationType: {
        info: null;
    } | {
        deadline: null;
    } | {
        payment: null;
    };
    createdAt: _Time;
    read: boolean;
    message: string;
}): {
    id: bigint;
    title: string;
    userId: Principal;
    notificationType: Variant_info_deadline_payment;
    createdAt: Time;
    read: boolean;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        notificationType: from_candid_variant_n24(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    };
    clientId: bigint;
    techBankDetails: string;
    timeIn: _Time;
    clientPaid: boolean;
    visitLocation: string;
    techAgreedRate: bigint;
    createdAt: _Time;
    visitDate: _Time;
    totalTime: bigint;
    projectHandleClient: string;
    updatedAt: _Time;
    progress: bigint;
    techDetails: string;
    clientAgreedRate: bigint;
    travelCost: bigint;
    profit: bigint;
    timeOut: _Time;
    materialCost: bigint;
    clientCompanyName: string;
    projectHandleTeam: string;
    techPaid: boolean;
}): {
    id: bigint;
    status: Variant_cancelled_pending_completed;
    clientId: bigint;
    techBankDetails: string;
    timeIn: Time;
    clientPaid: boolean;
    visitLocation: string;
    techAgreedRate: bigint;
    createdAt: Time;
    visitDate: Time;
    totalTime: bigint;
    projectHandleClient: string;
    updatedAt: Time;
    progress: bigint;
    techDetails: string;
    clientAgreedRate: bigint;
    travelCost: bigint;
    profit: bigint;
    timeOut: Time;
    materialCost: bigint;
    clientCompanyName: string;
    projectHandleTeam: string;
    techPaid: boolean;
} {
    return {
        id: value.id,
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        techBankDetails: value.techBankDetails,
        timeIn: value.timeIn,
        clientPaid: value.clientPaid,
        visitLocation: value.visitLocation,
        techAgreedRate: value.techAgreedRate,
        createdAt: value.createdAt,
        visitDate: value.visitDate,
        totalTime: value.totalTime,
        projectHandleClient: value.projectHandleClient,
        updatedAt: value.updatedAt,
        progress: value.progress,
        techDetails: value.techDetails,
        clientAgreedRate: value.clientAgreedRate,
        travelCost: value.travelCost,
        profit: value.profit,
        timeOut: value.timeOut,
        materialCost: value.materialCost,
        clientCompanyName: value.clientCompanyName,
        projectHandleTeam: value.projectHandleTeam,
        techPaid: value.techPaid
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    draft: null;
}): Variant_paid_unpaid_draft {
    return "paid" in value ? Variant_paid_unpaid_draft.paid : "unpaid" in value ? Variant_paid_unpaid_draft.unpaid : "draft" in value ? Variant_paid_unpaid_draft.draft : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    info: null;
} | {
    deadline: null;
} | {
    payment: null;
}): Variant_info_deadline_payment {
    return "info" in value ? Variant_info_deadline_payment.info : "deadline" in value ? Variant_info_deadline_payment.deadline : "payment" in value ? Variant_info_deadline_payment.payment : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): Variant_cancelled_pending_completed {
    return "cancelled" in value ? Variant_cancelled_pending_completed.cancelled : "pending" in value ? Variant_cancelled_pending_completed.pending : "completed" in value ? Variant_cancelled_pending_completed.completed : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n26(_uploadFile, _downloadFile, x));
}
function to_candid_Invoice_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_cancelled_pending_completed;
    clientId: bigint;
    techBankDetails: string;
    timeIn: Time;
    clientPaid: boolean;
    visitLocation: string;
    techAgreedRate: bigint;
    createdAt: Time;
    visitDate: Time;
    totalTime: bigint;
    projectHandleClient: string;
    updatedAt: Time;
    progress: bigint;
    techDetails: string;
    clientAgreedRate: bigint;
    travelCost: bigint;
    profit: bigint;
    timeOut: Time;
    materialCost: bigint;
    clientCompanyName: string;
    projectHandleTeam: string;
    techPaid: boolean;
}): {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    };
    clientId: bigint;
    techBankDetails: string;
    timeIn: _Time;
    clientPaid: boolean;
    visitLocation: string;
    techAgreedRate: bigint;
    createdAt: _Time;
    visitDate: _Time;
    totalTime: bigint;
    projectHandleClient: string;
    updatedAt: _Time;
    progress: bigint;
    techDetails: string;
    clientAgreedRate: bigint;
    travelCost: bigint;
    profit: bigint;
    timeOut: _Time;
    materialCost: bigint;
    clientCompanyName: string;
    projectHandleTeam: string;
    techPaid: boolean;
} {
    return {
        id: value.id,
        status: to_candid_variant_n11(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        techBankDetails: value.techBankDetails,
        timeIn: value.timeIn,
        clientPaid: value.clientPaid,
        visitLocation: value.visitLocation,
        techAgreedRate: value.techAgreedRate,
        createdAt: value.createdAt,
        visitDate: value.visitDate,
        totalTime: value.totalTime,
        projectHandleClient: value.projectHandleClient,
        updatedAt: value.updatedAt,
        progress: value.progress,
        techDetails: value.techDetails,
        clientAgreedRate: value.clientAgreedRate,
        travelCost: value.travelCost,
        profit: value.profit,
        timeOut: value.timeOut,
        materialCost: value.materialCost,
        clientCompanyName: value.clientCompanyName,
        projectHandleTeam: value.projectHandleTeam,
        techPaid: value.techPaid
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_paid_unpaid_draft;
    lineItems: Array<InvoiceLineItem>;
    ourCompanyName: string;
    taxPercent: bigint;
    clientWebsite: string;
    createdAt: Time;
    clientEmail: string;
    dueDate: Time;
    discountPercent: bigint;
    ourEmail: string;
    clientAddress: string;
    grandTotal: bigint;
    invoiceDate: Time;
    ourWebsite: string;
    updatedAt: Time;
    invoiceNumber: string;
    projectId: bigint;
    costCenter: string;
    clientPhone: string;
    ourAddress: string;
    ourPhone: string;
    paymentTerms: string;
    clientCompanyName: string;
    subtotal: bigint;
    invoiceMonth: string;
}): {
    id: bigint;
    status: {
        paid: null;
    } | {
        unpaid: null;
    } | {
        draft: null;
    };
    lineItems: Array<_InvoiceLineItem>;
    ourCompanyName: string;
    taxPercent: bigint;
    clientWebsite: string;
    createdAt: _Time;
    clientEmail: string;
    dueDate: _Time;
    discountPercent: bigint;
    ourEmail: string;
    clientAddress: string;
    grandTotal: bigint;
    invoiceDate: _Time;
    ourWebsite: string;
    updatedAt: _Time;
    invoiceNumber: string;
    projectId: bigint;
    costCenter: string;
    clientPhone: string;
    ourAddress: string;
    ourPhone: string;
    paymentTerms: string;
    clientCompanyName: string;
    subtotal: bigint;
    invoiceMonth: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n5(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        ourCompanyName: value.ourCompanyName,
        taxPercent: value.taxPercent,
        clientWebsite: value.clientWebsite,
        createdAt: value.createdAt,
        clientEmail: value.clientEmail,
        dueDate: value.dueDate,
        discountPercent: value.discountPercent,
        ourEmail: value.ourEmail,
        clientAddress: value.clientAddress,
        grandTotal: value.grandTotal,
        invoiceDate: value.invoiceDate,
        ourWebsite: value.ourWebsite,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        projectId: value.projectId,
        costCenter: value.costCenter,
        clientPhone: value.clientPhone,
        ourAddress: value.ourAddress,
        ourPhone: value.ourPhone,
        paymentTerms: value.paymentTerms,
        clientCompanyName: value.clientCompanyName,
        subtotal: value.subtotal,
        invoiceMonth: value.invoiceMonth
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: Principal;
    notificationType: Variant_info_deadline_payment;
    createdAt: Time;
    read: boolean;
    message: string;
}): {
    id: bigint;
    title: string;
    userId: Principal;
    notificationType: {
        info: null;
    } | {
        deadline: null;
    } | {
        payment: null;
    };
    createdAt: _Time;
    read: boolean;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        notificationType: to_candid_variant_n8(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_completed): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == Variant_cancelled_pending_completed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_completed.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_paid_unpaid_draft): {
    paid: null;
} | {
    unpaid: null;
} | {
    draft: null;
} {
    return value == Variant_paid_unpaid_draft.paid ? {
        paid: null
    } : value == Variant_paid_unpaid_draft.unpaid ? {
        unpaid: null
    } : value == Variant_paid_unpaid_draft.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_info_deadline_payment): {
    info: null;
} | {
    deadline: null;
} | {
    payment: null;
} {
    return value == Variant_info_deadline_payment.info ? {
        info: null
    } : value == Variant_info_deadline_payment.deadline ? {
        deadline: null
    } : value == Variant_info_deadline_payment.payment ? {
        payment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
